name: "Regression Testing with GitHub App token"
on:
  push:
    branches:
      - main

jobs:
  regression-test:
    name: Regression Testing with GitHub App token
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          path: ghas-metrics-report
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN:  ${{ steps.get_workflow_token.outputs.token }}
          RUN_USING_ACT: "true"
        with:
          repo: "ghas-metrics-report"
          org: "advanced-security-demo"
          features: "dependabot, code-scanning, secret-scanning"
