name: "Regression Testing using local provided PAT"
on:
  workflow_dispatch:

jobs:
  regression-local-pat:
    name: Regression Testing with local PAT
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          path: ghas-metrics-report
      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN: ${{ steps.token-collection.outputs.token }}
          RUN_USING_ACT: "true"
        with:
          repo: "srdemo-demo"
          org: "advanced-security-demo"
          features: "dependabot, code-scanning, secret-scanning"
