name: "Regression Testing using local provided PAT"
on:
  pull_request_target:
  
jobs:
  regression-local-pat:
    name: Regression Testing with local PAT
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          path: ghas-metrics-report
      - name: 'Set build id'
        id: build_id
        run: echo "::set-output name=id::$(date +%s)"
      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN: ${{ steps.token-collection.outputs.token }}
          RUN_USING_ACT: "true"
          repo: "srdemo-demo"
          org: "advanced-security-demo"
        # with: 
        #   repo: X
        #   org: "X"
        


